-- Opens the class diagram:
-- open examples/Papers/2005/GogollaBohlingRichters/percom.use

-- Creates the object diagram:
-- read examples/Papers/2005/GogollaBohlingRichters/percom-3-X.cmd

-- Script generated by USE 2.0.0-generator_1.01

!create Company1,Company2 : Company
!set Company1.name := 'Sony'
!set Company2.name := 'Lex'
!create Person1,Person2,Person3 : Person
!set Person1.name := 'Cher'
!set Person2.name := 'Tom'
!set Person3.name := 'Nick'
!create Job1,Job2,Job3,Job4,Job5,Job6 : Job
!insert (Person1,Job1) into PersonJob
!insert (Company1,Job1) into CompanyJob
!insert (Person2,Job2) into PersonJob
!insert (Company2,Job2) into CompanyJob
!insert (Person3,Job3) into PersonJob
!insert (Company1,Job3) into CompanyJob
!insert (Person1,Job4) into PersonJob
!insert (Company2,Job4) into CompanyJob
!insert (Person2,Job5) into PersonJob
!insert (Company1,Job5) into CompanyJob
!insert (Person3,Job6) into PersonJob
!insert (Company2,Job6) into CompanyJob
!insert (Job1,Job3) into BossWorker
!insert (Job1,Job5) into BossWorker
!insert (Job2,Job4) into BossWorker
!insert (Job4,Job6) into BossWorker
!set Job1.salary := 5500
!set Job2.salary := 5500
!set Job3.salary := 3000
!set Job4.salary := 3500
!set Job5.salary := 4500
!set Job6.salary := 2500
