-- Opens the class diagram:
-- open examples/Papers/2005/GogollaBohlingRichters/percom.use

-- Creates the object diagram:
-- read examples/Papers/2005/GogollaBohlingRichters/percom-10-X.cmd

-- Script generated by USE 2.0.0-generator_1.01

!create Person1,Person2,Person3,Person4,Person5,Person6,Person7 : Person
!set Person1.name := 'Dan'
!set Person2.name := 'Ida'
!set Person3.name := 'Fred'
!set Person4.name := 'Eva'
!set Person5.name := 'Hal'
!set Person6.name := 'Lisa'
!set Person7.name := 'Gil'
!create Company1 : Company
!set Company1.name := 'Miro'
!create Job1,Job2,Job3,Job4,Job5,Job6,Job7 : Job
!insert (Person1,Job1) into PersonJob
!insert (Company1,Job1) into CompanyJob
!insert (Person2,Job2) into PersonJob
!insert (Company1,Job2) into CompanyJob
!insert (Person3,Job3) into PersonJob
!insert (Company1,Job3) into CompanyJob
!insert (Person4,Job4) into PersonJob
!insert (Company1,Job4) into CompanyJob
!insert (Person5,Job5) into PersonJob
!insert (Company1,Job5) into CompanyJob
!insert (Person6,Job6) into PersonJob
!insert (Company1,Job6) into CompanyJob
!insert (Person7,Job7) into PersonJob
!insert (Company1,Job7) into CompanyJob
!set Job2.salary := 4500
!set Job1.salary := 5000
!insert (Job1,Job2) into BossWorker
!set Job3.salary := 5000
!set Job1.salary := 5500
!insert (Job1,Job3) into BossWorker
!set Job4.salary := 5000
!set Job2.salary := 5500
!insert (Job2,Job4) into BossWorker
!set Job5.salary := 4000
!set Job4.salary := 4500
!insert (Job4,Job5) into BossWorker
!set Job6.salary := 4000
!set Job2.salary := 5000
!insert (Job2,Job6) into BossWorker
!set Job7.salary := 3500
!set Job4.salary := 4500
!insert (Job4,Job7) into BossWorker
