-- Script generated by USE 2.5.1B2

!create class_A : Class
!create class_B : Class
!create property_A_name : Property
!insert (class_A,property_A_name) into A_Classifier_Classifier_Property_Attribute
!delete (class_A,property_A_name) from A_Classifier_Classifier_Property_Attribute
!insert (class_A,property_A_name) into A_Classifier_Classifier_NamedElement_InheritedMember
!delete (class_A,property_A_name) from A_Classifier_Classifier_NamedElement_InheritedMember
!insert (class_A,property_A_name) into C_Class_Class_Property_OwnedAttribute
