-- Opens the class diagram:
-- open examples/Papers/2003/Ziemann_2003_FMICS/bart.use

-- Creates the object diagram:
-- read examples/Papers/2003/Ziemann_2003_FMICS/run.cmd

read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
read step.cmd
