-- Script generated by USE 2.6.0B2

!create classA : Class
!set classA.name := 'A'
!create classB : Class
!set classB.name := 'B'
!create A_A_B : Association
!set A_A_B.name := 'A_A_B'
!insert (A_A_B,classB) into A_Association_Association_Type_EndType
!insert (A_A_B,classA) into A_Association_Association_Type_EndType
!create roleA : Property
!set roleA.name := 'a'
!create roleB : Property
!set roleB.name := 'b'
!insert (roleB,A_A_B) into A_Property_MemberEnd_Association_Association
!insert (roleA,A_A_B) into A_Property_MemberEnd_Association_Association
!create Class1 : Class
!destroy Class1
!create classC : Class
!create classD : Class
!create A_C_D : Association
!set classC.name := 'C'
!set classD.name := 'D'
!set A_C_D.name := 'A_C_D'
!insert (A_C_D,classC) into A_Association_Association_Type_EndType
!insert (A_C_D,classD) into A_Association_Association_Type_EndType
!create roleC : Property
!create roleD : Property
!set roleD.name := 'roleD'
!set roleC.name := 'roleC'
!insert (roleC,A_C_D) into A_Property_MemberEnd_Association_Association
!insert (roleD,A_C_D) into A_Property_MemberEnd_Association_Association
!insert (roleD,roleB) into A_Property_Property_Property_SubsettedProperty
!insert (roleC,roleA) into A_Property_Property_Property_SubsettedProperty
!insert (classC,classA) into A_Class_Class_Class_SuperClass
!insert (classB,classD) into A_Class_Class_Class_SuperClass
