open Sudoku.use
!create board : Board
!create Row1,Row2,Row3,Row4,Row5,Row6,Row7,Row8,Row9 : Row

!create Column1,Column2,Column3,Column4,Column5,Column6,Column7,Column8,Column9 : Column 

!create Square1,Square2,Square3,Square4,Square5,Square6,Square7,Square8,Square9 : Square 

!create Field1,Field2,Field3,Field4,Field5,Field6,Field7,Field8,Field9,Field10,Field11,Field12,Field13,Field14,Field15,Field16,Field17,Field18,Field19,Field20,Field21,Field22,Field23,Field24,Field25,Field26,Field27,Field28,Field29,Field30,Field31,Field32,Field33,Field34,Field35,Field36,Field37,Field38,Field39,Field40,Field41,Field42,Field43,Field44,Field45,Field46,Field47,Field48,Field49,Field50,Field51,Field52,Field53,Field54,Field55,Field56,Field57,Field58,Field59,Field60,Field61,Field62,Field63,Field64,Field65,Field66,Field67,Field68,Field69,Field70,Field71,Field72,Field73,Field74,Field75,Field76,Field77,Field78,Field79,Field80,Field81 : Field 

!set Column1.index := 1
!insert (board,Column1) into BoardColumns
!set Column2.index := 2
!insert (board,Column2) into BoardColumns
!set Column3.index := 3
!insert (board,Column3) into BoardColumns
!set Column4.index := 4
!insert (board,Column4) into BoardColumns
!set Column5.index := 5
!insert (board,Column5) into BoardColumns
!set Column6.index := 6
!insert (board,Column6) into BoardColumns
!set Column7.index := 7
!insert (board,Column7) into BoardColumns
!set Column8.index := 8
!insert (board,Column8) into BoardColumns
!set Column9.index := 9
!insert (board,Column9) into BoardColumns
!set Row1.index := 1
!insert (board,Row1) into BoardRows
!set Row2.index := 2
!insert (board,Row2) into BoardRows
!set Row3.index := 3
!insert (board,Row3) into BoardRows
!set Row4.index := 4
!insert (board,Row4) into BoardRows
!set Row5.index := 5
!insert (board,Row5) into BoardRows
!set Row6.index := 6
!insert (board,Row6) into BoardRows
!set Row7.index := 7
!insert (board,Row7) into BoardRows
!set Row8.index := 8
!insert (board,Row8) into BoardRows
!set Row9.index := 9
!insert (board,Row9) into BoardRows
!set Square1.index := 1
!insert (board,Square1) into BoardSquares
!set Square2.index := 2
!insert (board,Square2) into BoardSquares
!set Square3.index := 3
!insert (board,Square3) into BoardSquares
!set Square4.index := 4
!insert (board,Square4) into BoardSquares
!set Square5.index := 5
!insert (board,Square5) into BoardSquares
!set Square6.index := 6
!insert (board,Square6) into BoardSquares
!set Square7.index := 7
!insert (board,Square7) into BoardSquares
!set Square8.index := 8
!insert (board,Square8) into BoardSquares
!set Square9.index := 9
!insert (board,Square9) into BoardSquares
!insert (board,Field1) into BoardFields
!insert (Row1,Field1) into RowFields
!insert (Column1,Field1) into ColumnFields
!insert (Square1,Field1) into SquareFields
!insert (board,Field10) into BoardFields
!insert (Row2,Field10) into RowFields
!insert (Column1,Field10) into ColumnFields
!insert (Square4,Field10) into SquareFields
!insert (board,Field19) into BoardFields
!insert (Row3,Field19) into RowFields
!insert (Column1,Field19) into ColumnFields
!insert (Square7,Field19) into SquareFields
!insert (board,Field28) into BoardFields
!insert (Row4,Field28) into RowFields
!insert (Column1,Field28) into ColumnFields
!insert (Square1,Field28) into SquareFields
!insert (board,Field37) into BoardFields
!insert (Row5,Field37) into RowFields
!insert (Column1,Field37) into ColumnFields
!insert (Square4,Field37) into SquareFields
!insert (board,Field46) into BoardFields
!insert (Row6,Field46) into RowFields
!insert (Column1,Field46) into ColumnFields
!insert (Square7,Field46) into SquareFields
!insert (board,Field55) into BoardFields
!insert (Row7,Field55) into RowFields
!insert (Column1,Field55) into ColumnFields
!insert (Square1,Field55) into SquareFields
!insert (board,Field64) into BoardFields
!insert (Row8,Field64) into RowFields
!insert (Column1,Field64) into ColumnFields
!insert (Square4,Field64) into SquareFields
!insert (board,Field73) into BoardFields
!insert (Row9,Field73) into RowFields
!insert (Column1,Field73) into ColumnFields
!insert (Square7,Field73) into SquareFields
!insert (board,Field2) into BoardFields
!insert (Row1,Field2) into RowFields
!insert (Column2,Field2) into ColumnFields
!insert (Square2,Field2) into SquareFields
!insert (board,Field11) into BoardFields
!insert (Row2,Field11) into RowFields
!insert (Column2,Field11) into ColumnFields
!insert (Square5,Field11) into SquareFields
!insert (board,Field20) into BoardFields
!insert (Row3,Field20) into RowFields
!insert (Column2,Field20) into ColumnFields
!insert (Square8,Field20) into SquareFields
!insert (board,Field29) into BoardFields
!insert (Row4,Field29) into RowFields
!insert (Column2,Field29) into ColumnFields
!insert (Square2,Field29) into SquareFields
!insert (board,Field38) into BoardFields
!insert (Row5,Field38) into RowFields
!insert (Column2,Field38) into ColumnFields
!insert (Square5,Field38) into SquareFields
!insert (board,Field47) into BoardFields
!insert (Row6,Field47) into RowFields
!insert (Column2,Field47) into ColumnFields
!insert (Square8,Field47) into SquareFields
!insert (board,Field56) into BoardFields
!insert (Row7,Field56) into RowFields
!insert (Column2,Field56) into ColumnFields
!insert (Square2,Field56) into SquareFields
!insert (board,Field65) into BoardFields
!insert (Row8,Field65) into RowFields
!insert (Column2,Field65) into ColumnFields
!insert (Square5,Field65) into SquareFields
!insert (board,Field74) into BoardFields
!insert (Row9,Field74) into RowFields
!insert (Column2,Field74) into ColumnFields
!insert (Square8,Field74) into SquareFields
!insert (board,Field3) into BoardFields
!insert (Row1,Field3) into RowFields
!insert (Column3,Field3) into ColumnFields
!insert (Square3,Field3) into SquareFields
!insert (board,Field12) into BoardFields
!insert (Row2,Field12) into RowFields
!insert (Column3,Field12) into ColumnFields
!insert (Square6,Field12) into SquareFields
!insert (board,Field21) into BoardFields
!insert (Row3,Field21) into RowFields
!insert (Column3,Field21) into ColumnFields
!insert (Square9,Field21) into SquareFields
!insert (board,Field30) into BoardFields
!insert (Row4,Field30) into RowFields
!insert (Column3,Field30) into ColumnFields
!insert (Square3,Field30) into SquareFields
!insert (board,Field39) into BoardFields
!insert (Row5,Field39) into RowFields
!insert (Column3,Field39) into ColumnFields
!insert (Square6,Field39) into SquareFields
!insert (board,Field48) into BoardFields
!insert (Row6,Field48) into RowFields
!insert (Column3,Field48) into ColumnFields
!insert (Square9,Field48) into SquareFields
!insert (board,Field57) into BoardFields
!insert (Row7,Field57) into RowFields
!insert (Column3,Field57) into ColumnFields
!insert (Square3,Field57) into SquareFields
!insert (board,Field66) into BoardFields
!insert (Row8,Field66) into RowFields
!insert (Column3,Field66) into ColumnFields
!insert (Square6,Field66) into SquareFields
!insert (board,Field75) into BoardFields
!insert (Row9,Field75) into RowFields
!insert (Column3,Field75) into ColumnFields
!insert (Square9,Field75) into SquareFields
!insert (board,Field4) into BoardFields
!insert (Row1,Field4) into RowFields
!insert (Column4,Field4) into ColumnFields
!insert (Square1,Field4) into SquareFields
!insert (board,Field13) into BoardFields
!insert (Row2,Field13) into RowFields
!insert (Column4,Field13) into ColumnFields
!insert (Square4,Field13) into SquareFields
!insert (board,Field22) into BoardFields
!insert (Row3,Field22) into RowFields
!insert (Column4,Field22) into ColumnFields
!insert (Square7,Field22) into SquareFields
!insert (board,Field31) into BoardFields
!insert (Row4,Field31) into RowFields
!insert (Column4,Field31) into ColumnFields
!insert (Square1,Field31) into SquareFields
!insert (board,Field40) into BoardFields
!insert (Row5,Field40) into RowFields
!insert (Column4,Field40) into ColumnFields
!insert (Square4,Field40) into SquareFields
!insert (board,Field49) into BoardFields
!insert (Row6,Field49) into RowFields
!insert (Column4,Field49) into ColumnFields
!insert (Square7,Field49) into SquareFields
!insert (board,Field58) into BoardFields
!insert (Row7,Field58) into RowFields
!insert (Column4,Field58) into ColumnFields
!insert (Square1,Field58) into SquareFields
!insert (board,Field67) into BoardFields
!insert (Row8,Field67) into RowFields
!insert (Column4,Field67) into ColumnFields
!insert (Square4,Field67) into SquareFields
!insert (board,Field76) into BoardFields
!insert (Row9,Field76) into RowFields
!insert (Column4,Field76) into ColumnFields
!insert (Square7,Field76) into SquareFields
!insert (board,Field5) into BoardFields
!insert (Row1,Field5) into RowFields
!insert (Column5,Field5) into ColumnFields
!insert (Square2,Field5) into SquareFields
!insert (board,Field14) into BoardFields
!insert (Row2,Field14) into RowFields
!insert (Column5,Field14) into ColumnFields
!insert (Square5,Field14) into SquareFields
!insert (board,Field23) into BoardFields
!insert (Row3,Field23) into RowFields
!insert (Column5,Field23) into ColumnFields
!insert (Square8,Field23) into SquareFields
!insert (board,Field32) into BoardFields
!insert (Row4,Field32) into RowFields
!insert (Column5,Field32) into ColumnFields
!insert (Square2,Field32) into SquareFields
!insert (board,Field41) into BoardFields
!insert (Row5,Field41) into RowFields
!insert (Column5,Field41) into ColumnFields
!insert (Square5,Field41) into SquareFields
!insert (board,Field50) into BoardFields
!insert (Row6,Field50) into RowFields
!insert (Column5,Field50) into ColumnFields
!insert (Square8,Field50) into SquareFields
!insert (board,Field59) into BoardFields
!insert (Row7,Field59) into RowFields
!insert (Column5,Field59) into ColumnFields
!insert (Square2,Field59) into SquareFields
!insert (board,Field68) into BoardFields
!insert (Row8,Field68) into RowFields
!insert (Column5,Field68) into ColumnFields
!insert (Square5,Field68) into SquareFields
!insert (board,Field77) into BoardFields
!insert (Row9,Field77) into RowFields
!insert (Column5,Field77) into ColumnFields
!insert (Square8,Field77) into SquareFields
!insert (board,Field6) into BoardFields
!insert (Row1,Field6) into RowFields
!insert (Column6,Field6) into ColumnFields
!insert (Square3,Field6) into SquareFields
!insert (board,Field15) into BoardFields
!insert (Row2,Field15) into RowFields
!insert (Column6,Field15) into ColumnFields
!insert (Square6,Field15) into SquareFields
!insert (board,Field24) into BoardFields
!insert (Row3,Field24) into RowFields
!insert (Column6,Field24) into ColumnFields
!insert (Square9,Field24) into SquareFields
!insert (board,Field33) into BoardFields
!insert (Row4,Field33) into RowFields
!insert (Column6,Field33) into ColumnFields
!insert (Square3,Field33) into SquareFields
!insert (board,Field42) into BoardFields
!insert (Row5,Field42) into RowFields
!insert (Column6,Field42) into ColumnFields
!insert (Square6,Field42) into SquareFields
!insert (board,Field51) into BoardFields
!insert (Row6,Field51) into RowFields
!insert (Column6,Field51) into ColumnFields
!insert (Square9,Field51) into SquareFields
!insert (board,Field60) into BoardFields
!insert (Row7,Field60) into RowFields
!insert (Column6,Field60) into ColumnFields
!insert (Square3,Field60) into SquareFields
!insert (board,Field69) into BoardFields
!insert (Row8,Field69) into RowFields
!insert (Column6,Field69) into ColumnFields
!insert (Square6,Field69) into SquareFields
!insert (board,Field78) into BoardFields
!insert (Row9,Field78) into RowFields
!insert (Column6,Field78) into ColumnFields
!insert (Square9,Field78) into SquareFields
!insert (board,Field7) into BoardFields
!insert (Row1,Field7) into RowFields
!insert (Column7,Field7) into ColumnFields
!insert (Square1,Field7) into SquareFields
!insert (board,Field16) into BoardFields
!insert (Row2,Field16) into RowFields
!insert (Column7,Field16) into ColumnFields
!insert (Square4,Field16) into SquareFields
!insert (board,Field25) into BoardFields
!insert (Row3,Field25) into RowFields
!insert (Column7,Field25) into ColumnFields
!insert (Square7,Field25) into SquareFields
!insert (board,Field34) into BoardFields
!insert (Row4,Field34) into RowFields
!insert (Column7,Field34) into ColumnFields
!insert (Square1,Field34) into SquareFields
!insert (board,Field43) into BoardFields
!insert (Row5,Field43) into RowFields
!insert (Column7,Field43) into ColumnFields
!insert (Square4,Field43) into SquareFields
!insert (board,Field52) into BoardFields
!insert (Row6,Field52) into RowFields
!insert (Column7,Field52) into ColumnFields
!insert (Square7,Field52) into SquareFields
!insert (board,Field61) into BoardFields
!insert (Row7,Field61) into RowFields
!insert (Column7,Field61) into ColumnFields
!insert (Square1,Field61) into SquareFields
!insert (board,Field70) into BoardFields
!insert (Row8,Field70) into RowFields
!insert (Column7,Field70) into ColumnFields
!insert (Square4,Field70) into SquareFields
!insert (board,Field79) into BoardFields
!insert (Row9,Field79) into RowFields
!insert (Column7,Field79) into ColumnFields
!insert (Square7,Field79) into SquareFields
!insert (board,Field8) into BoardFields
!insert (Row1,Field8) into RowFields
!insert (Column8,Field8) into ColumnFields
!insert (Square2,Field8) into SquareFields
!insert (board,Field17) into BoardFields
!insert (Row2,Field17) into RowFields
!insert (Column8,Field17) into ColumnFields
!insert (Square5,Field17) into SquareFields
!insert (board,Field26) into BoardFields
!insert (Row3,Field26) into RowFields
!insert (Column8,Field26) into ColumnFields
!insert (Square8,Field26) into SquareFields
!insert (board,Field35) into BoardFields
!insert (Row4,Field35) into RowFields
!insert (Column8,Field35) into ColumnFields
!insert (Square2,Field35) into SquareFields
!insert (board,Field44) into BoardFields
!insert (Row5,Field44) into RowFields
!insert (Column8,Field44) into ColumnFields
!insert (Square5,Field44) into SquareFields
!insert (board,Field53) into BoardFields
!insert (Row6,Field53) into RowFields
!insert (Column8,Field53) into ColumnFields
!insert (Square8,Field53) into SquareFields
!insert (board,Field62) into BoardFields
!insert (Row7,Field62) into RowFields
!insert (Column8,Field62) into ColumnFields
!insert (Square2,Field62) into SquareFields
!insert (board,Field71) into BoardFields
!insert (Row8,Field71) into RowFields
!insert (Column8,Field71) into ColumnFields
!insert (Square5,Field71) into SquareFields
!insert (board,Field80) into BoardFields
!insert (Row9,Field80) into RowFields
!insert (Column8,Field80) into ColumnFields
!insert (Square8,Field80) into SquareFields
!insert (board,Field9) into BoardFields
!insert (Row1,Field9) into RowFields
!insert (Column9,Field9) into ColumnFields
!insert (Square3,Field9) into SquareFields
!insert (board,Field18) into BoardFields
!insert (Row2,Field18) into RowFields
!insert (Column9,Field18) into ColumnFields
!insert (Square6,Field18) into SquareFields
!insert (board,Field27) into BoardFields
!insert (Row3,Field27) into RowFields
!insert (Column9,Field27) into ColumnFields
!insert (Square9,Field27) into SquareFields
!insert (board,Field36) into BoardFields
!insert (Row4,Field36) into RowFields
!insert (Column9,Field36) into ColumnFields
!insert (Square3,Field36) into SquareFields
!insert (board,Field45) into BoardFields
!insert (Row5,Field45) into RowFields
!insert (Column9,Field45) into ColumnFields
!insert (Square6,Field45) into SquareFields
!insert (board,Field54) into BoardFields
!insert (Row6,Field54) into RowFields
!insert (Column9,Field54) into ColumnFields
!insert (Square9,Field54) into SquareFields
!insert (board,Field63) into BoardFields
!insert (Row7,Field63) into RowFields
!insert (Column9,Field63) into ColumnFields
!insert (Square3,Field63) into SquareFields
!insert (board,Field72) into BoardFields
!insert (Row8,Field72) into RowFields
!insert (Column9,Field72) into ColumnFields
!insert (Square6,Field72) into SquareFields
!insert (board,Field81) into BoardFields
!insert (Row9,Field81) into RowFields
!insert (Column9,Field81) into ColumnFields
!insert (Square9,Field81) into SquareFields
