-- Script generated by USE 2.5.1B2

!create b1 : Boat
!create e1 : Engine
!create p1 : Propeller
!insert (b1,p1) into C_InBoat_P
!insert (b1,p1) into C_InVehicle_Part
!insert (b1,p1) into C_InVehicle_PowerTransmitter
!insert (e1,p1) into powers
!insert (b1,e1) into C_InVehicle_Part
!insert (b1,e1) into C_InVehicle_PowerSource
