-- Script generated by USE 2.5.1B2

!create b1 : Boat
!create e1 : Engine
!create p1 : Propeller
!insert (b1,p1) into C_InBoat_P
!insert (b1,p1) into C_InVehicle_Part
!insert (b1,p1) into C_InVehicle_PowerTransmitter
!insert (e1,p1) into powers
!insert (b1,e1) into C_InVehicle_Part
!insert (b1,e1) into C_InVehicle_PowerSource
!create c1 : Car
!create e2 : Engine
!create w1 : Wheel
!create w2 : Wheel
!create w3 : Wheel
!create w4 : Wheel
!insert (c1,w1) into C_InCarAsFront_Front
!insert (c1,w2) into C_InCarAsFront_Front
!insert (c1,w1) into C_InVehicle_PowerTransmitter
!insert (c1,w2) into C_InVehicle_PowerTransmitter
!insert (c1,w3) into C_InCarAsBack_Back
!insert (c1,w4) into C_InCarAsBack_Back
!insert (c1,e2) into C_InVehicle_PowerSource
!insert (e2,w1) into powers
!insert (e2,w2) into powers
