-- Opens the class diagram:
-- open examples/Documentation/AssociationClass/AssociationClass.use

-- Creates the object diagram:
-- read examples/Documentation/AssociationClass/AssociationClass.cmd

-- Script generated by USE 2.2.0-devel

!create c1 : Company
!create p1 : Person
!create worksFor1:WorksFor between (c1,p1)

!create p2 : Person
!create employeeRanking:EmployeeRanking between (p2,p2)
