package org.tzi.use.mapper;

import org.mapstruct.Mapper;
import org.mapstruct.MappingConstants;
import org.tzi.use.DTO.ModelDTO;
import org.tzi.use.entities.ModelNTT;

/**
 * MapStruct mapper to convert between ModelNTT (entity) and ModelDTO (data transfer object).
 * Implementation will be generated by MapStruct at compile time and registered as a Spring bean.
 */
@Mapper(componentModel = MappingConstants.ComponentModel.SPRING)
public interface ModelMapper {

    ModelDTO toDTO(ModelNTT entity);

    ModelNTT toEntity(ModelDTO dto);
}
