module use.gui {
    requires transitive use.core;
    requires transitive vtd.xml;
    requires itextpdf;
    requires javafx.fxml;
    requires transitive javafx.web;
    requires org.kordamp.desktoppanefx.core;
    requires transitive javafx.swing;
    requires annotations;
    requires static lombok;
    requires com.google.common;
    requires transitive java.desktop;
    requires transitive java.xml;
    requires transitive javafx.graphics;
    requires transitive javafx.controls;
    opens org.tzi.use.gui.main to javafx.fxml;
    exports org.tzi.use.main.gui;
    exports org.tzi.use.gui.views;
    exports org.tzi.use.gui.main;
    exports org.tzi.use.gui.util;
    exports org.tzi.use.gui.views.diagrams.behavior.communicationdiagram;
    exports org.tzi.use.gui.views.diagrams.classdiagram;
    exports org.tzi.use.gui.views.diagrams.objectdiagram;
    exports org.tzi.use.runtime.spi;
    exports org.tzi.use.gui.plugin;
    exports org.tzi.use.main.shell;
    exports org.tzi.use.gui.mainFX;
    exports org.tzi.use.gui.mainFX.runtime;
    opens org.tzi.use.gui.mainFX to javafx.fxml;
    exports org.tzi.use.gui.pluginFX;
    exports org.tzi.use.gui.utilFX;
    exports org.tzi.use.gui.viewsFX.evalbrowser;
    exports org.tzi.use.gui.views.diagrams;
    exports org.tzi.use.gui.views.diagrams.framework;
    exports org.tzi.use.gui.views.diagrams.behavior.shared to com.google.common;
    exports org.tzi.use.gui.views.diagrams.selection to com.google.common;
    exports org.tzi.use.gui.views.diagrams.statemachine to com.google.common;
    exports org.tzi.use.gui.views.diagrams.elements;
    exports org.tzi.use.gui.views.diagrams.elements.edges;
    exports org.tzi.use.gui.main.runtime;
    exports org.tzi.use.gui.views.diagrams.util;
    exports org.tzi.use.gui.views.diagrams.selection.objectselection;
    exports org.tzi.use.gui.views.diagrams.event;
    exports org.tzi.use.runtime.model;
    exports org.tzi.use.gui.views.diagrams.waypoints;
    exports org.tzi.use.gui.views.diagrams.elements.positioning;
}